name: todo_list
description: A quick todo list app

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^1.1.3
  path_provider: ^0.5.0+1
  google_maps_flutter: ^0.5.0
  rxdart: ^0.21.0
  date_format: ^1.0.6
  google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.3
  cloud_firestore: ^0.9.9
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass/Overpass-Regular.ttf
        - asset: assets/fonts/Overpass/Overpass-Italic.ttf
          style: italic
        - asset: assets/fonts/Overpass/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/Overpass/Overpass-Bold.ttf
          weight: 700
